### ISSUE TITLE
[메시지]

### ISSUE THREAD

**Issue by foodieon** [dooboolab/foodieon_admin#1]
@dooboolab 

게스트가 호스트에게 메시지를 보냈을때

1) 호스트에게 메시지 push 알림 도착

**2) 호스트 모드로 전환하고 메시지 탭바를 클릭했는데 메세지가 없음**

-------------------------------------------------------------------------------

게스트가 호스트에게 메시지를 보냈을때

1) 메인 메시지 탭 바 클릭시 호스트에게 메시지 보낸내용이 안보임

**Comment by dooboolab** [comment]
Moved https://github.com/dooboolab/foodieon/issues/7.
