### ISSUE TITLE
트립 지역 선택시 트립 정보가 안보임

### ISSUE THREAD

**Issue by foodieon** [dooboolab/foodieon_admin#2]
@dooboolab 

안드로이드 / ios 공통

메인화면에서

◆ 서울 클릭 -> 서울에 위치한 트립 정보가 뜨지 않음(2개 등록한 트립)

◆  어디로 가시나요? 검색바 클릭 -> 서울 클릭 -> 서울에 위치한 트립 정보가 뜨지 않음(2개 등록한 트립)

**Comment by dooboolab** [comment]
Moved https://github.com/dooboolab/foodieon/issues/8
