### ISSUE TITLE
[트립등록 오류] 안드로이드 트립 등록시 

### ISSUE THREAD

**Issue by foodieon** [dooboolab/foodieon_admin#3]
@dooboolab 

안드로이드 트립 등록시 

◈ 주의사항 옵션 선택이 안되게 되어있음

![_ _](https://user-images.githubusercontent.com/40194154/47731312-2e587b80-dca7-11e8-8e3d-fd77c4333228.jpg)

**Comment by dooboolab** [comment]
Moved https://github.com/dooboolab/foodieon/issues/9.
